### ISSUE TITLE
Can't extract netfxsdk.msi

### ISSUE THREAD

**Issue by voltagex** [activescott/lessmsi#122]
**Describe the bug**

Extracting the MSI from .NET FX SDK 1.1 gets the following error:

```
---------------------------
MSI Error!
---------------------------
Please report this error at https://github.com/activescott/lessmsi/issues . Include the exact error message and how to get a copy of the msi you're working with.

The following error occured extracting the MSI: System.Exception: Error copying file 'C:\Users\Adam\Desktop\netfxsd1.cab' to 'C:\Users\Adam\Desktop\netfxsd1.cab'. System error information:'The operation completed successfully.

'

   at LessIO.Strategies.Win32.Win32FileSystemStrategy.Copy(Path source, Path dest)

   at LessMsi.Msi.Wixtracts.CabsFromMsiToDisk(Path msi, Database msidb, String outputDir)

   at LessMsi.Msi.Wixtracts.ExtractFiles(Path msi, String outputDir, MsiFile[] filesToExtract, AsyncCallback progressCallback)

   at LessMsi.Gui.MainForm.btnExtract_Click(Object sender, EventArgs e)
---------------------------
OK   
---------------------------

```

**To Reproduce**
1. Download https://download.microsoft.com/download/5/2/0/5202f918-306e-426d-9637-d7ee26fbe507/setup.exe (https://www.microsoft.com/en-us/download/confirmation.aspx?id=16217)
2. Extract the msi and CAB from setup.exe using 7zip
3. Extract with lessmsi-gui

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/159567/53247846-7133d880-3708-11e9-90dc-368af9e42b08.png)

**Desktop (please complete the following information):**
Windows 10 1809, lessmsi 1.6.1.0

**Additional context**

**Comment by voltagex** [comment]
When testing with git head in VS2019:

![image](https://user-images.githubusercontent.com/159567/53279088-c5b77200-3761-11e9-969f-e64f155f584e.png)

**Comment by activescott** [comment]
Thanks @voltagex . Since you got the source out in git, did you plan to work on a fix or not? Just don't want to duplicate efforts.

**Comment by activescott** [comment]
Just to make sure we maintain access to it, I have uploaded this file to dropbox and made it available at https://www.dropbox.com/s/s0ha3u3ckggnhpf/setup-exe-for-less-msi-issue-122.zip?dl=0

**Comment by voltagex** [comment]
At this stage I'm not working on a fix as I was able to get the files I needed by ignoring that assert! It looks like it behaves better in the current version, at least.

Thanks for your quick response.

**Comment by jjurkus** [comment]
No issues with 1.6.91!
