### ISSUE TITLE
This msi file references a CAB file that is not embedded inside of the msi file itself.

### ISSUE THREAD

**Issue by xRageHead** [activescott/lessmsi#164]
This msi file references a CAB file that is not embedded inside of the msi file itself. The msi file is named Media1.cab and was expected to be in the following folder: C:\Users\j4846\AppData\Local\Temp\Rar$DRa0.702\title_update_7_EN

Technical Detail:

   at LessMsi.Msi.Wixtracts.CabsFromMsiToDisk(Path msi, Database msidb, String outputDir)
   at LessMsi.Msi.Wixtracts.ExtractFiles(Path msi, String outputDir, MsiFile[] filesToExtract, AsyncCallback progressCallback)
   at LessMsi.Gui.MainForm.btnExtract_Click(Object sender, EventArgs e)

**Comment by activescott** [comment]
Thanks @xRageHead. Do you have the msi file so we can test by chance?
