### ISSUE TITLE
my msi isnt working

### ISSUE THREAD

**Issue by treaki** [activescott/lessmsi#51]
hi,

my msi file isnt working:

```
E:\temp_>e:\lessmsi-v1.3\lessmsi.exe x "{F7FC242D-A96D-4051-8C80-D1F5301EE36E}\P
rezi.msi" prex
Extracting 'E:\temp_\{F7FC242D-A96D-4051-8C80-D1F5301EE36E}\Prezi.msi' to 'E:\te
mp_\Prezi'.
File prex was not found in the msi.
^C
E:\temp_>e:\lessmsi-v1.3\lessmsi.exe x "{F7FC242D-A96D-4051-8C80-D1F5301EE36E}\P
rezi.msi" prex\
Extracting 'E:\temp_\{F7FC242D-A96D-4051-8C80-D1F5301EE36E}\Prezi.msi' to 'E:\te
mp_\prex\'.

Error: System.IO.IOException: IO operation will not work. Most likely the file w
ill become too long or the handle was not opened to support synchronous IO opera
tions.
   at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.FileStream.Write(Byte[] array, Int32 offset, Int32 count)
   at System.IO.BinaryWriter.Write(Byte[] buffer, Int32 index, Int32 count)
   at LessMsi.Msi.Wixtracts.ExtractCabFromPackage(String filePath, String cabNam
e, Database inputDatabase)
   at LessMsi.Msi.Wixtracts.CabsFromMsiToDisk(FileInfo msi, Database msidb, Dire
ctoryInfo outputDir)
   at LessMsi.Msi.Wixtracts.ExtractFiles(FileInfo msi, DirectoryInfo outputDir,
MsiFile[] filesToExtract, AsyncCallback progressCallback)
   at LessMsi.Msi.Wixtracts.ExtractFiles(FileInfo msi, DirectoryInfo outputDir,
String[] fileNamesToExtract)
   at LessMsi.Cli.Program.DoExtraction(String msiFileName, String outDirName, Li
st`1 filesToExtract)
   at LessMsi.Cli.ExtractCommand.Run(List`1 allArgs)
   at LessMsi.Cli.Program.Main(String[] args)

Usage:
lessmsi <command> [options] <msi_name> [<path_to_extract\>] [file_names]

Commands:
  x  Extracts all or specified files from the specified msi_name.
  l  Lists the contents of the specified msi table as CSV to stdout.
  v  Lists the value of the ProductVersion Property in the msi
     (typically this is the version of the MSI).
  o  Opens the specified msi_name in the GUI.
  h  Shows this help page.

For more information see http://lessmsi.activescott.com


E:\temp_>
```

**Comment by treaki** [comment]
sry, my fault, disk was full. but a more specific error message on this would be helpful

**Comment by activescott** [comment]
Thanks for the follow-up. We'd have to do an extra explicit check for disk space since Windows doesn't give us a great error here. Feels like we shouldn't do that for now, but let me know if you disagree.
